//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP2_DB2_Antusevich
{
    using System;
    using System.Collections.Generic;
    
    public partial class Склад
    {
        public int ID_Склада { get; set; }
        public string Название { get; set; }
        public string Адрес { get; set; }
        public Nullable<int> Вместимость { get; set; }
        public Nullable<int> ID_Продукции { get; set; }
    
        public virtual Продукция Продукция { get; set; }
    }
}
