//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP2_DB2_Antusevich
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        public int ID_Сотрудника { get; set; }
        public string ФИО { get; set; }
        public string Должность { get; set; }
        public Nullable<System.DateTime> Дата_Приема_На_Работу { get; set; }
        public Nullable<int> ID_Производства { get; set; }
    
        public virtual Производство Производство { get; set; }
    }
}
